favicon: null
name: Digital Life
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1738351
  brandStrength: 0
  lightness: 0.5215054
  brandColors:
    - '#ffffff'
    - '#931c80'
    - '#7286dc'
    - '#c38c00'
    - '#128a04'
  rhythmicContrast: 0.4336918
typography_spectrum: 0.6738351
layout_spectrum: 0.5268817
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
