name: Digital Life
favicon: null
layout_spectrum: 0.8193402569741011
typography_spectrum: 0.7424392187967896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#931c80'
    - '#7286dc'
    - '#c38c00'
    - '#128a04'
  brandStrength: 0.5
  lightness: 0.8932128783781081
  saturation: 0.701950722374022
  rhythmicContrast: 0.9827278880402446
purpose: []
