title: The Digital Journey of Spenno
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.297491
  lightness: 1
  brandColors:
    - '#ffc86e'
    - '#ffffff'
    - '#a2f28f'
    - '#5b6b6b'
    - '#000000'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Digital Life
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6738351
layout_spectrum: 0.530466
