name: Digital Life
favicon: null
layout_spectrum: 0.530466
typography_spectrum: 0.6738351
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Digital Journey of Spenno
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffc86e'
    - '#ffffff'
    - '#a2f28f'
    - '#5b6b6b'
    - '#000000'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
